from .logistic_baseline import LogisticBaseline
from .mlp_baseline import MLPBaseline
from .cnn1d import CNN1D
from .residual_cnn import ResidualCNN
from .cnn_attention import CNNAttention
from .rc_dilated_bigru_gated import RCDilatedCNNBiGRUGated
from .deepsea_model import DeepSEAStyle
from .danq_model import DanQStyle
from .basenji_style_model import BasenjiStyle
